// <auto-generated />
using IllusionPackageDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IllusionPackageManagerBackend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220129010206_q")]
    partial class q
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("IllusionPackageDatabase.PackageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("IllusionPackageDatabase.PackageModel", b =>
                {
                    b.OwnsOne("System.Version", "Version", b1 =>
                        {
                            b1.Property<int>("PackageModelId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PackageModelId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageModelId");
                        });

                    b.Navigation("Version")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
